name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: Urara12/Training-Timer
        with:
          project: test
          column: TODO
          repo-token: ${{ secrets.GITHUB_TOKEN }}
